### ISSUE TITLE
Allow user to set default value for BAGIS-P parameter

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-p#10]
There is a request to set some BAGIS-P parameters to a single constant value, ie: 0. Current approach is to create a model for each of these parameters and configure it to always return the desired constant. This works within the existing BAGIS-P framework with no code changes required.

An alternative approach is to modify the bagis_parameters.txt control file that lists the parameters calculated by BAGIS-P and their dimensions. We could add another column with the default value. If this value is present we would use it. Otherwise would get the value(s) from the model. Requires some code changes but parameters could be controlled using the control file in the future.

**Comment by jdduh** [comment]
The suggested approach to adding new column seems feasible. However, BAGIS-P must make it clear to users that some of the parameters are set by default values defined in the txt file. If the users overlook this feature, they might think BAGIS-P generated erroneous results and look in the wrong place (e.g., tbx models) for troubleshooting.

**Comment by jdduh** [comment]
Please close this enhancement request. I have created models for setting a parameter to a single value. Your proposed approach could cause additional issues because we don't have a local copy of the txt file.
