### ISSUE TITLE
Unable to delete an entry from the settings.xml using the Data Manager (Public)

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#12]
![image](https://cloud.githubusercontent.com/assets/11510708/9949743/0db4c6cc-5d66-11e5-9c24-a8fd7415b912.png)

**Comment by lbross** [comment]
Bug was introduced when changing AOI Data from a checkbox to a text column. Fixed and new add-in version posted in releases.
