### ISSUE TITLE
Add status field to ParameterExport form

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-p#13]
Exporting the parameters is taking noticeably longer now that some additional processing has been added. Recommend adding a status field like we have on the ProfileBuilder so the user doesn't think that BAGIS-P has stopped working.

**Comment by jdduh** [comment]
Yes, please add the message dialog.

**Comment by jdduh** [comment]
Additional bug reports. Let me know if you need the AOI that I was using.

1) I still get this error message when using George's template.

![image](https://cloud.githubusercontent.com/assets/11510708/10206206/8be1f7d6-677a-11e5-9dd2-8a21169be766.png)

2) Got this error message when the export tool was calculating the jh_coef for the AOI.

![image](https://cloud.githubusercontent.com/assets/11510708/10206268/dbf15852-677a-11e5-81ae-91e334b7c80e.png)

**Comment by jdduh** [comment]
I think the first error triggered the second one. When I use a different template, the export tool completed the process.

**Comment by lbross** [comment]
If the Parameter Export needs to work with George's template can you attach a copy of the .csv to this issue and I will see what the problem is?

Actually, opening a new issue would be better.

**Comment by jdduh** [comment]
Please rename .txt to .csv. Github doesn't support .csv file upload.

[BAGIS_Parameters_from_George.txt](https://github.com/PSU-CSAR/vb-bagis-p/files/5593/BAGIS_Parameters_from_George.txt)

**Comment by lbross** [comment]
Opened issue #14 to track this bug separately from status field enhancement.

**Comment by lbross** [comment]
Wait ... message. Wants message to flash. Remove border from text box.

**Comment by lbross** [comment]
Changed message to scroll from right-to-left. Seemed less obnoxious than blinking but still indicated processing. It doesn't work perfectly. Still locks when the GP tool is running but hopefully an improvement. The blinking also requires a timer so it would lock as well.

**Comment by jdduh** [comment]
Have you tried to show an animated gif image (e.g., spinning hourglass) when the process begins and hide the image after the process stops? I wonder if the animated gif is also affected by the GP tool locks. The error handling code block needs to hide the image when an error interrupts the process.

**Comment by lbross** [comment]
I posted a version of the add-in so you can see how the scrolling message looks/works. 

If this isn't acceptable, we should try the animation-only ProgressDialog that you wrote for BAGIS V2H. It looks like it is used when creating an AOI.

**Comment by lbross** [comment]
Just added another add-in version with "spin" in the name so you can see how the animation-only ProgressDialog looks:

https://github.com/PSU-CSAR/vb-bagis-p/releases/tag/1.9.1

**Comment by lbross** [comment]
Scrolling box with message has been implemented in v1.9.2
