### ISSUE TITLE
Local profile builder

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-p#18]
1. Make txtStatus flash
2. Add toggle button to set selected to unselected and vice versa

**Comment by lbross** [comment]
Set version to 1.9.1

**Comment by lbross** [comment]
Add 'Toggle Use' button to screen to toggle 'Use' column on method grid. Moved status box up to accommodate this button.

Are you sure we need to have txtStatus scroll like the Parameter Export? I found that it's not as easy as changing the control properties. It requires a timer and keeping track of the current message. We update the message on ProfileBuilder more frequently than Parameter Export. If it's not an issue with users, we might want to leave as-is. Thoughts?

**Comment by jdduh** [comment]
As long as we make it clear that the process is still running, the user probably doesn't need to know which process is actually running. I think flashing text will do the trick. I don't notice the scrolling text of the parameter export. Which one do you refer to?

**Comment by lbross** [comment]
Toggle button added to ProfileBuilder. Will leave status textbox as-is as it works well on this form.
