### ISSUE TITLE
Export Parameters: Validate re-sampled HRU layer against HRU_ID column in nhru table

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-p#20]
Need to have a matching row in the re-sampled HRU grid for every HRU_ID entry in the nhru parameters table. Throw error message and halt export if there is a mismatch.

Note that with the current flow, the re-sampling takes place near the end of the export process so there may be a slight delay before we know this is a problem. The early parts of the export process (except for the jh_coeff calculation) run quickly. Is it a problem to save this reconciliation until the end?

**Comment by jdduh** [comment]
Is it possible to check the number of records in the raster attribute table to get a "count" of HRU number? It's fine to stop the process at the later part of the export if a mismatch is detected. Will the parameter file be written to the drive by then? It's OK if the parameter file is generated.

**Comment by lbross** [comment]
Yes, we can just validate the record count in the re-sampled raster against the nhru value if you feel this is sufficient. It would be faster.

The parameter file will have been written to the drive by then but the zip file won't have been created. There will also be a temporary working folderbut I can delete that if there is a mismatch.

**Comment by lbross** [comment]
Fixed in v1.9.3.
