### ISSUE TITLE
Export Parameters - Allow column sorting on Edit HRU Parameter table

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#24]
The function allows users to edit the records more efficiently. For example, by sorting the table on hru_elev, users can manually update the hru_deplcrv values for HRUs above timberline.

**Comment by lbross** [comment]
Column sorting was turned off on this table because the default behavior was to sort the values as strings rather than numbers. I was able to change this and table is now sortable by all columns.

**Comment by lbross** [comment]
Fixed in v1.9.3.

**Comment by jdduh** [comment]
The same column sorting issue for the Parameter Viewer. Please sort the values as numbers, not strings.

**Comment by lbross** [comment]
Need more information on this. Parameter Viewer appears to already be sorting correctly on my sample AOI's. Am I looking at the right form?

**Comment by jdduh** [comment]
![image](https://cloud.githubusercontent.com/assets/11510708/12102034/1617bc98-b2ed-11e5-9129-873cf0018994.png)
