### ISSUE TITLE
Timberline tool - Bing maps aerial not available

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#25]
The Bing maps service is not widely available. Is if possible to replace it with an ESRI basemap layer, e.g., Imagery (World_Imagery)?

**Comment by lbross** [comment]
This tool can load any layer from ArcGIS Online as a basemap layer but we need to have the ArcGIS.com package id which is derived from the url. I have updated BAGIS-P to use the ArcGIS Imagery base layer as recommend on ArcGIS.com as an alternative to Bing Maps, but if you find a layer on ArcGIS.com that would be better, this is easy to change.

ArcGIS.com imagery base layer: http://www.arcgis.com/home/item.html?id=483b230c56a44c33beb13f9b9ab9f88d

**Comment by lbross** [comment]
Fixed in v1.9.3.
