### ISSUE TITLE
Data Manager's clipping creates NODATA cells near AOI boundary

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#28]
Due the different raster cell sizes of the input databin layers, the clipped 900m PRISM and 1000m STATSGO soil data don't cover the AOI completely. Please use the p_aoi (buffered AOI) layer to clip databin layers that have a coarse resolution (more than 10 times coarser than the dem). If this additional rule makes the programming difficult, then just use the p_aoi to clip all the layers.

**Comment by lbross** [comment]
Add BA_SelectRasterClipFile to ProfileModule to select AOI Clip File based upon the comparative resolutions of the filled dem and clip files. This update will be included in the next release of BAGIS-P.
