### ISSUE TITLE
BAGIS-P export: basin_area value is incorrect for the sprague AOI.

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#29]
The sprague AOI that I posted on the ftp server produced a wrong basin_area value due to that the AOI boundary contains more than one polygons. I vaguely remember that BAGIS buffers the AOI vector slightly (1 meter?) to prevent the separation of polygons that touch by a corner. Is there a way to add up the areas of all polygons to produce a correct area value?

**Comment by lbross** [comment]
Added loop to sum the areas of all polygons in grid_v file. Before the fix sprague AOI reported an area of 0.12. After the fix, it reports an area of 1017993.34. This fix will be included in the next version of BAGIS-P.
