### ISSUE TITLE
Global profile/method editor unable to open

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#32]
When the user went through multiple updates on their profile/method folder, the xml files in the method/profile folder became "corrupted." As a result, an error message prevents the profile editor or method editor from opening. 

![image](https://cloud.githubusercontent.com/assets/11510708/19371789/0b593a7c-916b-11e6-9d2f-661be030d21c.png)

After reinitialized the global method and profile folders, the issue was resolved. Is there a way to improve the error handling routine of these dialog windows?

**Comment by lbross** [comment]
For these 'failed to open form' exceptions, I wrap the form initialization subroutine in a try- catch to catch any exceptions. If I don't do this and there is an exception, ArcMap will crash. As we learn what exceptions generally occur, we can code defensively for them. In this case, I changed the code to check and see if the key is already in the Hashtable before it tries to add it. This should prevent this exception from occurring in the future.

**Comment by lbross** [comment]
Fixed in v1.9.8
