### ISSUE TITLE
What determines the order of the parameters written to the output parameter file?

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#34]
NWCC prefers the output parameters are ordered alphabetically.

**Comment by lbross** [comment]
Are you talking about the spatial (nhru) parameters in the table? They retain the order from the input table. The single value parameters at the top of the file are already sorted alphabetically.

**Comment by lbross** [comment]
After looking at the code, the BAGIS-P parameters are printed first in whatever order they are in the parameter.gdb. Then it appends any non-BAGIS spatial parameters. I can add the alphabetical sort but it will require putting everything in some sort of structure before writing it to the .csv. This will likely not be done by Monday.

**Comment by lbross** [comment]
nhru parameters are now sorted alphabetically by name. Fixed in 1.9.8.
