### ISSUE TITLE
Public Profile Builder failed to open when the BAGIS folder is missing

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#36]
This is an odd error. One user didn't set the BAGIS environment variable, so her BAGIS folder is set to a well-known path. Everything (BAGIS (-H)) worked fine until she tried to open the public Profile Builder in BAGIS-P. Another user had the BAGIS environment variable set correctly, but put the BAGIS-P profile and method folders in the wrong place. They both got the same error message (which I don't recall), but were able to resolve the problem when the profile and method folder were put on the correct location.

I know BAGIS-P will create profile and method folders if it cannot locate them. But it seemed to be not the case for both users. You probably need to put an error handling routine for the creation of the profile and method folders so that, if the attempt fails, the user gets a descriptive message about what had happened. Something like "Cannot locate BAGIS-P profile and methods folders! Error occurred when creating the profile and method folders in [file path]."

**Comment by lbross** [comment]
Added suggested error message to Profile Builder if it cannot locate them. Fixed in 1.9.8
