### ISSUE TITLE
Export tool - hru_radpl value isn't set correctly

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-p#41]
The parameter "hru_radpl" needs to be the same as the HRU number, however, it appears not to do this when the HRU number in the basin exceeds the number in the parameter template file.  For example, if the current template has 82 HRUs, and in a basin with 105 HRUs, the hru_radpl values are 82 for HRUs 83-105.

**Comment by lbross** [comment]
Just ran a test using BAGIS_Parameters_from_George.csv as template with 82 HRUs against an AOI with 197 and "hru_radpl" is being populated correctly. This is a column in the 'Parameter bound by nhru' table, correct?
Is the user using the most current version of BAGIS-P? (v1.98. with date of 11/21/2016 in the add-in manager). If so, the easiest next step would be to send me the template. If I'm unable to recreate with that, then I will also need the problematic AOI.

**Comment by jdduh** [comment]
I'm using the correct add-in (though the About BAGIS-P dialog window still shows version 1.9.7). The result and the template files are attached. You can rename them back to csv.
[BAGIS_Parameters - Copy.txt](https://github.com/PSU-CSAR/vb-bagis-p/files/1372490/BAGIS_Parameters.-.Copy.txt)
[yampa_export.txt](https://github.com/PSU-CSAR/vb-bagis-p/files/1372493/yampa_export.txt)

**Comment by lbross** [comment]
This remains a mystery. The hru_radpl column is copied directly from the parameters table with no modifications by the VB code. Can you open your parameters table in ArcMap and see if the data is bad there too? This column is populated by a model called 'hru_radpl' in the bagis_topographic_methods.tbx. It is a simple model that copies the HRU_ID into the hru_radpl column. 

If the data in the hru_radpl column in the parameters table is bad, you may want to try recalculating the parameters and see if that fixes it. If the data is still bad there may be some sort of a problem with the model.

If the hru_radpl column in the parameters table looks good then there is something very strange going on. You will need to post the AOI so I can run it through the debugger.

**Comment by jdduh** [comment]
Here is a screenshot of the params table. The numbers in the HRU_ID field look correct. Do we rely on a model to transfer the HRU_ID value to hru_radpl? If that's the case, then I just need to add that model to the profile. I thought the hru_radpl value is propagated by the Export tool of BAGIS-P.

![image](https://user-images.githubusercontent.com/11510708/31422023-f32a2c4c-adff-11e7-9902-4930ef11a954.png)

**Comment by jdduh** [comment]
After adding back the model, the export file has the correct hru_radpl values. Thanks!
