### ISSUE TITLE
Updates to parameter export for ngw and nssr

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-p#52]
Change request from George L. 
1. Set ngw and nssr's values to the same as nhru
2. Set ngw and nssr's len value to the same as nhur and adjust their table length (i.e., the number of rows) to the same as what's indicated by the len value

Notes: This will only apply if parameters/tables exist in the parameter template file. The values from the first row of the template will be duplicated in the subsequent rows. BAGIS-P does not currently generate these parameters/tables.

**Comment by jdduh** [comment]
Message from George: "The new version of BAGIS-P provides the requested modifications. Looks good. Thanks for your help and pass along my thanks to Lesley as well. Appreciate everyone's help."
