### ISSUE TITLE
What happens when a layer is clipped to an aoi a second time?

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-p#7]
Forgot to define units the first time. Redefined data layer in public manager. Reclipped. But units were still not there. Preferred behavior is to silently overwrite but there may be a file lock issue where it can't be replaced in the same session.

**Comment by lbross** [comment]
Current functionality is to not overwrite the existing data layer in the AOI. A message shows on the Public data manager indicating that the layer already exists. Updating code in accordance with new requirements.

**Comment by jdduh** [comment]
Can you make it an option so that users can determine if they want to overwrite or skip the clipping process? An alternative way is to instruct the users to delete the layers manually in ArcCatalog before (re)clipping them to the AOI.

**Comment by lbross** [comment]
This should be possible. On Friday you said we should just silently delete the existing layer. Obviously giving the user the option is a little more complex. I'm seeing some strange behavior when trying to delete existing layers that I'm currently working through. Please let me know your preferred option.

**Comment by jdduh** [comment]
How about just modify the warning message and instruct the user to manually delete the layers in Catalog? You can list the path and layer name in the warning message so that it's easier to locate these files. So, you don't have to worry about file lock issues when deleting layers programmatically.

**Comment by lbross** [comment]
I would also like to add a pop-up message warning the user that one or more layers could not be clipped because they already exist. I think it might be too easy to miss the error message in the public data manager table. I think you and Gus did not see this message.
