### ISSUE TITLE
Maintain current AOI in BAGIS-P extension

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-p#9]
Check extension for aoi when a form is opened. If aoi previously selected then use that as current aoi

**Comment by lbross** [comment]
When I add this to the local profile builder, there is a significant delay before the form loads because of the extra processing. Not aware of a way to avoid this onLoad. Is this okay?

**Comment by jdduh** [comment]
If it's the same among of time it takes to set an AOI, then it's fine. Can you provide a message box indicating the AOI layers are being loaded so that the users know what's going on?

**Comment by lbross** [comment]
The problem from the user perspective is that the form isn't visible at all until it finishes loading. I can pop a messagebox saying that the form may take a few minutes to load but after that is dismissed, the application appears to be non-responsive until the form finishes loading. Tried Application.DoEvents this morning and that didn't help.

Another thought is to add a button next to the 'Set AOI' button that loads the current AOI. This would only be enabled if there is a current AOI. With this approach, the user would see the status messages on the form as they do when a new AOI is selected/set.

**Comment by jdduh** [comment]
The additional button "Use Current AOI" could work but not ideal. Have you tried the progress bar approach for displaying the message?

**Comment by lbross** [comment]
The StepProgressor helps. There is a slight delay when it pops up but not nearly as long as the form. Will move forward with this approach for loading current aoi when form is opened.

However, now behavior is different from using 'Set AOI' button. When the form is loaded from this button, we have a textbox on the form that updates the status. Do I leave this alone? Or use the StepProgressor for a new AOI as well?

**Comment by jdduh** [comment]
Please leave the textbox along, unless it might create maintenance concerns in the future.

**Comment by lbross** [comment]
Updated local profile builder, parameter viewer, parameter export, and local data manager forms to automatically load the current AOI if applicable. Added StepProgressor to local profile builder and data manager as those take longer to load. Posted new version of add-in under release 1.8.0.

**Comment by jdduh** [comment]
Could you extend the feature to the SubAOIID and Timberline tools?

**Comment by lbross** [comment]
Updated subAoiId and Timberline tools. New add-in posted to release 1.8.0
